// This file is auto-generated by scratch/fix_geography_labels.py
import pacaCitySlugs from "../paca-cities.json";

export const CITY_GEOGRAPHY: { [key: string]: { lat: number; lng: number; label: string } } = {
  "abu-dhabi": { lat: 24.4539, lng: 54.3773, label: "Abu Dhabi (Émirats arabes unis)" },
  "agen": { lat: 44.202304, lng: 0.631041, label: "Agen" },
  "aigues-vives": { lat: 43.729929, lng: 4.188601, label: "Aigues-Vives" },
  "aix-en-provence": { lat: 43.5297, lng: 5.4474, label: "Aix-en-Provence" },
  "ajaccio": { lat: 41.93368, lng: 8.715325, label: "Ajaccio" },
  "alameda": { lat: 49.2646, lng: -102.2825, label: "Alameda (Canada)" },
  "albertville": { lat: 45.671004, lng: 6.396774, label: "Albertville" },
  "ales": { lat: 44.125356, lng: 4.089242, label: "Alès" },
  "allenjoie": { lat: 47.531967, lng: 6.894065, label: "Allenjoie" },
  "alpes-de-haute-provence": { lat: 44.1675, lng: 6.219, label: "Alpes-de-Haute-Provence (04)" },
  "alpes-maritimes": { lat: 43.833, lng: 7.167, label: "Alpes-Maritimes (06)" },
  "amiens": { lat: 49.903041, lng: 2.292605, label: "Amiens" },
  "andernos-les-bains": { lat: 44.751412, lng: -1.083375, label: "Andernos-Les-Bains" },
  "angers": { lat: 47.467471, lng: -0.561615, label: "Angers" },
  "anglet": { lat: 43.488004, lng: -1.518997, label: "Anglet" },
  "angouleme": { lat: 45.644105, lng: 0.148008, label: "Angoulême" },
  "annecy": { lat: 45.901584, lng: 6.125296, label: "Annecy" },
  "annecy-le-vieux": { lat: 45.901584, lng: 6.125296, label: "Annecy" },
  "antibes": { lat: 43.5804, lng: 7.1251, label: "Antibes" },
  "arc-les-gray": { lat: 47.458613, lng: 5.582714, label: "Arc-Lçs-Gray" },
  "arcachon": { lat: 44.651462, lng: -1.173981, label: "Arcachon" },
  "arcueil": { lat: 48.805178, lng: 2.333471, label: "Arcueil" },
  "argenteuil": { lat: 48.948465, lng: 2.248202, label: "Argenteuil" },
  "arnouville": { lat: 48.986984, lng: 2.416319, label: "Arnouville" },
  "arques": { lat: 50.734524, lng: 2.305321, label: "Arques" },
  "arras": { lat: 50.287896, lng: 2.768267, label: "Arras" },
  "atlanta": { lat: 33.749, lng: -84.388, label: "Atlanta (États-Unis)" },
  "aubervilliers": { lat: 48.912878, lng: 2.386167, label: "Aubervilliers" },
  "aubusson": { lat: 45.948902, lng: 2.174535, label: "Aubusson" },
  "audrieu": { lat: 49.203647, lng: -0.600977, label: "Audrieu" },
  "aulnay-sous-bois": { lat: 48.940735, lng: 2.497929, label: "Aulnay-Sous-Bois" },
  "avallon": { lat: 47.484856, lng: 3.917279, label: "Avallon" },
  "avesnes-les-bapaume": { lat: 50.108136, lng: 2.842677, label: "Avesnes-Lçs-Bapaume" },
  "avignon": { lat: 43.936345, lng: 4.848861, label: "Avignon" },
  "avon": { lat: 48.412996, lng: 2.728925, label: "Avon" },
  "bagnols-en-foret": { lat: 43.539399, lng: 6.690304, label: "Bagnols-en-Forêt" },
  "bagnols-sur-ceze": { lat: 44.158426, lng: 4.624846, label: "Bagnols-sur-Céze" },
  "baie-mahault": { lat: 16.245166, lng: -61.594891, label: "Baie-Mahault" },
  "bailly-romainvilliers": { lat: 48.848981, lng: 2.815171, label: "Bailly-Romainvilliers" },
  "balma": { lat: 43.609803, lng: 1.50338, label: "Balma" },
  "barcelona": { lat: 41.3851, lng: 2.1734, label: "Barcelone (Espagne)" },
  "barcelone": { lat: 41.3851, lng: 2.1734, label: "Barcelone (Espagne)" },
  "barentin": { lat: 49.544169, lng: 0.949823, label: "Barentin" },
  "baume-les-dames": { lat: 47.349374, lng: 6.361718, label: "Baume-Les-Dames" },
  "beaucaire": { lat: 43.786319, lng: 4.601599, label: "Beaucaire" },
  "beaune": { lat: 47.025352, lng: 4.840893, label: "Beaune" },
  "beine-nauroy": { lat: 49.249236, lng: 4.21635, label: "Beine-Nauroy" },
  "bellegarde": { lat: 43.752857, lng: 4.495228, label: "Bellegarde" },
  "bergerac": { lat: 44.85304, lng: 0.482291, label: "Bergerac" },
  "berlin": { lat: 52.52, lng: 13.405, label: "Berlin (Allemagne)" },
  "bernin": { lat: 45.267187, lng: 5.867065, label: "Bernin" },
  "berre-l-etang": { lat: 43.509274, lng: 5.162227, label: "Berre-l'Étang" },
  "besancon": { lat: 47.251938, lng: 6.001699, label: "Besançon" },
  "bessines": { lat: 46.297382, lng: -0.51113, label: "Bessines" },
  "bezannes": { lat: 49.220632, lng: 3.997585, label: "Bezannes" },
  "beziers": { lat: 43.343264, lng: 3.233465, label: "Béziers" },
  "bezons": { lat: 48.927132, lng: 2.214879, label: "Bezons" },
  "biarritz": { lat: 43.472166, lng: -1.555076, label: "Biarritz" },
  "bidart": { lat: 43.437712, lng: -1.575579, label: "Bidart" },
  "biot": { lat: 43.627821, lng: 7.081617, label: "Biot" },
  "blainville-sur-orne": { lat: 49.230407, lng: -0.302196, label: "Blainville-Sur-Orne" },
  "blois": { lat: 47.581228, lng: 1.316533, label: "Blois" },
  "bobigny": { lat: 48.907365, lng: 2.443342, label: "Bobigny" },
  "bois-colombes": { lat: 48.915331, lng: 2.268837, label: "Bois-Colombes" },
  "bonneuil-sur-marne": { lat: 48.773398, lng: 2.489643, label: "Bonneuil-Sur-Marne" },
  "bordeaux": { lat: 44.8378, lng: -0.5792, label: "Bordeaux" },
  "boston": { lat: 42.3601, lng: -71.0589, label: "Boston (États-Unis)" },
  "bouches-du-rhone": { lat: 43.5297, lng: 5.4474, label: "Bouches-du-Rhône (13)" },
  "bouguenais": { lat: 47.172155, lng: -1.615684, label: "Bouguenais" },
  "boulay-les-barres": { lat: 47.977509, lng: 1.782206, label: "Boulay-Les-Barres" },
  "boulazac": { lat: 45.138859, lng: 0.783086, label: "Boulazac Isle Manoire" },
  "boulogne-billancourt": { lat: 48.837799, lng: 2.243202, label: "Boulogne-Billancourt" },
  "boulogne-sur-mer": { lat: 50.726334, lng: 1.607492, label: "Boulogne-Sur-Mer" },
  "bourg-les-valence": { lat: 44.962715, lng: 4.893636, label: "Bourg-Lçs-Valence" },
  "bourg-saint-maurice": { lat: 45.653657, lng: 6.787531, label: "Bourg-Saint-Maurice" },
  "bourges": { lat: 47.082882, lng: 2.402294, label: "Bourges" },
  "bresaint": { lat: 46.78493, lng: 5.795518, label: "Besain" },
  "briec": { lat: 48.096106, lng: -4.002044, label: "Briec" },
  "brignoles": { lat: 43.405995, lng: 6.073657, label: "Brignoles" },
  "bristol": { lat: 51.4545, lng: -2.5879, label: "Bristol (Royaume-Uni)" },
  "brussels": { lat: 50.8503, lng: 4.3517, label: "Bruxelles (Belgique)" },
  "bruxelles": { lat: 50.8503, lng: 4.3517, label: "Bruxelles (Belgique)" },
  "bruz": { lat: 48.02516, lng: -1.748362, label: "Bruz" },
  "buchelay": { lat: 48.981841, lng: 1.677671, label: "Buchelay" },
  "buchy": { lat: 49.586782, lng: 1.341072, label: "Buchy" },
  "cabourg": { lat: 49.286373, lng: -0.125678, label: "Cabourg" },
  "caen": { lat: 49.184316, lng: -0.37193, label: "Caen" },
  "cagnes-sur-mer": { lat: 43.661, lng: 7.1517, label: "Cagnes-sur-Mer" },
  "caissargues": { lat: 43.793041, lng: 4.38663, label: "Caissargues" },
  "cannes": { lat: 43.5528, lng: 7.0174, label: "Cannes" },
  "cannet": { lat: 43.5768, lng: 7.0189, label: "Le Cannet" },
  "carcans": { lat: 45.085103, lng: -1.055088, label: "Carcans" },
  "carros": { lat: 43.7925, lng: 7.1864, label: "Carros" },
  "cebu-city": { lat: 10.3167, lng: 123.8907, label: "Cebu City (Philippines)" },
  "cesson-sevigne": { lat: 48.123772, lng: -1.596972, label: "Cesson-Sévigné" },
  "chalampe": { lat: 47.826451, lng: 7.544409, label: "Chalampé" },
  "chalette-sur-loing": { lat: 48.019121, lng: 2.720474, label: "Châlette-sur-Loing" },
  "chalon-sur-saone": { lat: 46.792112, lng: 4.846002, label: "Chalon-sur-Saône" },
  "chalons-en-champagne": { lat: 48.955254, lng: 4.368278, label: "Châlons-en-Champagne" },
  "chambery": { lat: 45.583223, lng: 5.909299, label: "Chambéry" },
  "chambly": { lat: 49.170042, lng: 2.244676, label: "Chambly" },
  "chambourcy": { lat: 48.902406, lng: 2.041587, label: "Chambourcy" },
  "chambray-les-tours": { lat: 47.332303, lng: 0.717976, label: "Chambray-Lçs-Tours" },
  "champ-sur-drac": { lat: 45.076, lng: 5.732679, label: "Champ-Sur-Drac" },
  "chaponnay": { lat: 45.62714, lng: 4.956839, label: "Chaponnay" },
  "charleville-mezieres": { lat: 49.767639, lng: 4.71728, label: "Charleville-Mçziçres" },
  "charlieu": { lat: 46.162098, lng: 4.167319, label: "Charlieu" },
  "chartres": { lat: 48.446525, lng: 1.502286, label: "Chartres" },
  "chateau-gontier-sur-mayenne": { lat: 47.819956, lng: -0.694321, label: "Château-Gontier-sur-Mayenne" },
  "chateau-thierry": { lat: 49.050003, lng: 3.383835, label: "Chçteau-Thierry" },
  "chateauroux": { lat: 46.804353, lng: 1.692994, label: "Chçteauroux" },
  "chatellerault": { lat: 46.8162, lng: 0.551, label: "Châtellerault" },
  "chatillon": { lat: 48.803355, lng: 2.286345, label: "Châtillon" },
  "chaumont": { lat: 48.104307, lng: 5.129976, label: "Chaumont" },
  "chauny": { lat: 49.616374, lng: 3.2196, label: "Chauny" },
  "checy": { lat: 47.902112, lng: 2.020374, label: "Chécy" },
  "chennevieres-sur-marne": { lat: 48.794898, lng: 2.541501, label: "Chennevières-sur-Marne" },
  "cherbourg-en-cotentin": { lat: 49.628684, lng: -1.63324, label: "Cherbourg-En-Cotentin" },
  "chessy": { lat: 48.871441, lng: 2.764777, label: "Chessy" },
  "choisy-le-roi": { lat: 48.764115, lng: 2.412807, label: "Choisy-Le-Roi" },
  "chusclan": { lat: 44.148506, lng: 4.682979, label: "Chusclan" },
  "cleon": { lat: 49.315466, lng: 1.039203, label: "Cléon" },
  "clermont-ferrand": { lat: 45.786671, lng: 3.107055, label: "Clermont-Ferrand" },
  "cluses": { lat: 46.064209, lng: 6.575877, label: "Cluses" },
  "collonges-au-mont-d-or": { lat: 45.817865, lng: 4.841344, label: "Collonges-Au-Mont-D'Or" },
  "colmar": { lat: 48.081779, lng: 7.352569, label: "Colmar" },
  "colombelles": { lat: 49.194563, lng: -0.294056, label: "Colombelles" },
  "colombo": { lat: 47.661897, lng: 6.284696, label: "Colombotte" },
  "colomiers": { lat: 43.609804, lng: 1.32962, label: "Colomiers" },
  "compiegne": { lat: 49.405934, lng: 2.844366, label: "Compiègne" },
  "concarneau": { lat: 47.891735, lng: -3.896018, label: "Concarneau" },
  "courbevoie": { lat: 48.897974, lng: 2.257057, label: "Courbevoie" },
  "cournon-d-auvergne": { lat: 45.739285, lng: 3.18543, label: "Cournon-D'Auvergne" },
  "courrieres": { lat: 50.454139, lng: 2.943183, label: "Courrières" },
  "creil": { lat: 49.257474, lng: 2.4788, label: "Creil" },
  "crissey": { lat: 46.82029, lng: 4.879886, label: "Crissey" },
  "croissy-beaubourg": { lat: 48.821778, lng: 2.65357, label: "Croissy-Beaubourg" },
  "crolles": { lat: 45.283529, lng: 5.883069, label: "Crolles" },
  "deauville": { lat: 49.354643, lng: 0.073063, label: "Deauville" },
  "dieppe": { lat: 49.919877, lng: 1.086296, label: "Dieppe" },
  "dieuze": { lat: 48.811468, lng: 6.720321, label: "Dieuze" },
  "dijon": { lat: 47.331953, lng: 5.033601, label: "Dijon" },
  "dole": { lat: 47.077883, lng: 5.493658, label: "Dole" },
  "domene": { lat: 45.20279, lng: 5.834654, label: "Domène" },
  "dourges": { lat: 50.434738, lng: 2.985156, label: "Dourges" },
  "draguignan": { lat: 43.532153, lng: 6.459174, label: "Draguignan" },
  "drancy": { lat: 48.924157, lng: 2.444197, label: "Drancy" },
  "dubai": { lat: 25.2048, lng: 55.2708, label: "Dubaï (EAU)" },
  "dublin": { lat: 53.3498, lng: -6.2603, label: "Dublin (Irlande)" },
  "duppigheim": { lat: 48.534535, lng: 7.592083, label: "Duppigheim" },
  "dury": { lat: 49.858514, lng: 2.274577, label: "Dury" },
  "emerainville": { lat: 48.817648, lng: 2.611569, label: "Émerainville" },
  "entzheim": { lat: 48.537823, lng: 7.641038, label: "Entzheim" },
  "epernay": { lat: 49.040236, lng: 3.960527, label: "Épernay" },
  "epinal": { lat: 48.170226, lng: 6.484892, label: "Épinal" },
  "ergue-gaberic": { lat: 48.00655, lng: -4.010617, label: "Ergué-Gabéric" },
  "etampes": { lat: 48.427733, lng: 2.14952, label: "Étampes" },
  "etaples": { lat: 50.519262, lng: 1.653178, label: "Étaples" },
  "evreux": { lat: 49.020599, lng: 1.146898, label: "Évreux" },
  "evry-courcouronnes": { lat: 48.627362, lng: 2.433066, label: "Évry-Courcouronnes" },
  "farebersviller": { lat: 49.117534, lng: 6.871562, label: "Farébersviller" },
  "faverges-seythenex": { lat: 45.737295, lng: 6.286774, label: "Faverges-Seythenex" },
  "fes": { lat: 50.049707, lng: 3.707565, label: "Fesmy-Le-Sart" },
  "feyzin": { lat: 45.674658, lng: 4.858258, label: "Feyzin" },
  "flers": { lat: 48.737426, lng: -0.563453, label: "Flers" },
  "florange": { lat: 49.320972, lng: 6.128261, label: "Florange" },
  "flourens": { lat: 43.595564, lng: 1.55735, label: "Flourens" },
  "fontanil-cornillon": { lat: 45.253417, lng: 5.661775, label: "Fontanil-Cornillon" },
  "fontenay-sous-bois": { lat: 48.850004, lng: 2.473494, label: "Fontenay-Sous-Bois" },
  "fontenay-sur-eure": { lat: 48.399819, lng: 1.414377, label: "Fontenay-Sur-Eure" },
  "forbach": { lat: 49.190789, lng: 6.893798, label: "Forbach" },
  "fort-de-france": { lat: 14.636435, lng: -61.064096, label: "Fort-De-France" },
  "fos-sur-mer": { lat: 43.451226, lng: 4.933732, label: "Fos-Sur-Mer" },
  "fredericton": { lat: 45.9636, lng: -66.6431, label: "Fredericton (Canada)" },
  "frejus": { lat: 43.445657, lng: 6.770515, label: "Fréjus" },
  "fresnes": { lat: 48.757544, lng: 2.324537, label: "Fresnes" },
  "fretin": { lat: 50.563383, lng: 3.143035, label: "Fretin" },
  "frontignan": { lat: 43.443309, lng: 3.755072, label: "Frontignan" },
  "fuveau": { lat: 43.457385, lng: 5.554958, label: "Fuveau" },
  "gap": { lat: 44.563233, lng: 6.076778, label: "Gap" },
  "geispolsheim": { lat: 48.523153, lng: 7.677407, label: "Geispolsheim" },
  "gemenos": { lat: 43.296432, lng: 5.627895, label: "Gémenos" },
  "geneve": { lat: 46.2044, lng: 6.1432, label: "Genève (Suisse)" },
  "gennevilliers": { lat: 48.93113, lng: 2.294231, label: "Gennevilliers" },
  "gentilly": { lat: 48.812317, lng: 2.342606, label: "Gentilly" },
  "gerzat": { lat: 45.826063, lng: 3.151875, label: "Gerzat" },
  "gieres": { lat: 45.184369, lng: 5.790485, label: "Giçres" },
  "gif-sur-yvette": { lat: 48.694564, lng: 2.135009, label: "Gif-Sur-Yvette" },
  "gonesse": { lat: 48.985195, lng: 2.457867, label: "Gonesse" },
  "gonfreville-l-orcher": { lat: 49.510805, lng: 0.226063, label: "Gonfreville-L'Orcher" },
  "gouesnou": { lat: 48.443343, lng: -4.462844, label: "Gouesnou" },
  "gradignan": { lat: 44.7691, lng: -0.616651, label: "Gradignan" },
  "grasse": { lat: 43.6602, lng: 6.9265, label: "Grasse" },
  "gray": { lat: 47.440426, lng: 5.599432, label: "Gray" },
  "grenoble": { lat: 45.182828, lng: 5.724301, label: "Grenoble" },
  "guilers": { lat: 48.420019, lng: -4.559732, label: "Guilers" },
  "guyancourt": { lat: 48.772152, lng: 2.070346, label: "Guyancourt" },
  "halluin": { lat: 50.774135, lng: 3.125231, label: "Halluin" },
  "hautes-alpes": { lat: 44.667, lng: 6.333, label: "Hautes-Alpes (05)" },
  "heillecourt": { lat: 48.650256, lng: 6.197154, label: "Heillecourt" },
  "henin-beaumont": { lat: 50.420666, lng: 2.951562, label: "Hénin-Beaumont" },
  "hermival-les-vaux": { lat: 49.164626, lng: 0.282654, label: "Hermival-Les-Vaux" },
  "herouville-saint-clair": { lat: 49.203411, lng: -0.332375, label: "Hérouville-Saint-Clair" },
  "hyeres": { lat: 43.116731, lng: 6.20255, label: "Hyères" },
  "issy-les-moulineaux": { lat: 48.823903, lng: 2.262887, label: "Issy-Les-Moulineaux" },
  "itteville": { lat: 48.514657, lng: 2.345035, label: "Itteville" },
  "ivry-sur-seine": { lat: 48.812752, lng: 2.386427, label: "Ivry-Sur-Seine" },
  "l-isle-sur-la-sorgue": { lat: 43.91503, lng: 5.058675, label: "L'Isle-Sur-La-Sorgue" },
  "l-union": { lat: 43.651266, lng: 1.481564, label: "L'Union" },
  "la-brede": { lat: 44.678947, lng: -0.526691, label: "La Brède" },
  "la-garde": { lat: 43.127716, lng: 6.015518, label: "La Garde" },
  "la-madelaine-sous-montreuil": { lat: 50.467929, lng: 1.75062, label: "La Madelaine-Sous-Montreuil" },
  "la-maxe": { lat: 49.16111, lng: 6.186993, label: "La Maxe" },
  "la-montagne": { lat: 47.184208, lng: -1.680857, label: "La Montagne" },
  "la-mure": { lat: 44.913696, lng: 5.786486, label: "La Mure" },
  "la-norville": { lat: 48.585432, lng: 2.256509, label: "La Norville" },
  "la-petite-pierre": { lat: 48.856526, lng: 7.32623, label: "La Petite-Pierre" },
  "la-riche": { lat: 47.383957, lng: 0.637576, label: "La Riche" },
  "la-roche-sur-yon": { lat: 46.670848, lng: -1.412533, label: "La Roche-Sur-Yon" },
  "la-rochelle": { lat: 46.157457, lng: -1.170642, label: "La Rochelle" },
  "la-seyne-sur-mer": { lat: 43.093325, lng: 5.879651, label: "La Seyne-Sur-Mer" },
  "la-suze-sur-sarthe": { lat: 47.881391, lng: 0.023304, label: "La Suze-Sur-Sarthe" },
  "la-talaudiere": { lat: 45.477646, lng: 4.429392, label: "La Talaudière" },
  "lacroix-saint-ouen": { lat: 49.360902, lng: 2.785559, label: "Lacroix-Saint-Ouen" },
  "ladoix-serrigny": { lat: 47.064062, lng: 4.892051, label: "Ladoix-Serrigny" },
  "langres": { lat: 47.860319, lng: 5.337775, label: "Langres" },
  "lannion": { lat: 48.748795, lng: -3.469365, label: "Lannion" },
  "laon": { lat: 49.570287, lng: 3.614719, label: "Laon" },
  "lattes": { lat: 43.570523, lng: 3.900373, label: "Lattes" },
  "lauwin-planque": { lat: 50.392152, lng: 3.044971, label: "Lauwin-Planque" },
  "laval": { lat: 48.059596, lng: -0.77159, label: "Laval" },
  "laxou": { lat: 48.688106, lng: 6.141298, label: "Laxou" },
  "le-caire": { lat: 44.367393, lng: 6.057519, label: "Le Caire" },
  "le-canet": { lat: 43.5768, lng: 7.0189, label: "Le Cannet" },
  "le-cannet": { lat: 43.5768, lng: 7.0189, label: "Le Cannet" },
  "le-grand-quevilly": { lat: 49.409806, lng: 1.043854, label: "Le Grand-Quevilly" },
  "le-havre": { lat: 49.507345, lng: 0.129995, label: "Le Havre" },
  "le-mans": { lat: 47.993378, lng: 0.191169, label: "Le Mans" },
  "le-petit-quevilly": { lat: 49.422225, lng: 1.059571, label: "Le Petit-Quevilly" },
  "le-plessis-robinson": { lat: 48.781328, lng: 2.261065, label: "Le Plessis-Robinson" },
  "le-puy-sainte-reparade": { lat: 43.654056, lng: 5.437988, label: "Le Puy-Sainte-Rçparade" },
  "le-vieil-evreux": { lat: 49.005715, lng: 1.216058, label: "Le Vieil-Çvreux" },
  "lens": { lat: 50.437872, lng: 2.819642, label: "Lens" },
  "les-andelys": { lat: 49.245779, lng: 1.42127, label: "Les Andelys" },
  "les-pennes-mirabeau": { lat: 43.39829, lng: 5.326859, label: "Les Pennes-Mirabeau" },
  "les-ulis": { lat: 48.681532, lng: 2.185946, label: "Les Ulis" },
  "lesquin": { lat: 50.587214, lng: 3.111117, label: "Lesquin" },
  "levallois-perret": { lat: 48.894215, lng: 2.286846, label: "Levallois-Perret" },
  "levernois": { lat: 46.993454, lng: 4.874667, label: "Levernois" },
  "lezennes": { lat: 50.611529, lng: 3.116722, label: "Lezennes" },
  "lille": { lat: 50.6292, lng: 3.0573, label: "Lille" },
  "limay": { lat: 48.993097, lng: 1.735314, label: "Limay" },
  "limoux": { lat: 43.049781, lng: 2.237853, label: "Limoux" },
  "lisieux": { lat: 49.145761, lng: 0.242246, label: "Lisieux" },
  "lisses": { lat: 48.598234, lng: 2.432759, label: "Lisses" },
  "lombers": { lat: 43.811234, lng: 2.141291, label: "Lombers" },
  "lome": { lat: 43.045139, lng: 0.303131, label: "Lomé" },
  "london": { lat: 51.5074, lng: -0.1278, label: "Londres (Royaume-Uni)" },
  "londres": { lat: 51.5074, lng: -0.1278, label: "Londres (Royaume-Uni)" },
  "longeville-les-metz": { lat: 49.116766, lng: 6.141469, label: "Longeville-lès-Metz" },
  "longueil-sainte-marie": { lat: 49.342426, lng: 2.717611, label: "Longueil-Sainte-Marie" },
  "lons": { lat: 43.324331, lng: -0.406921, label: "Lons" },
  "lons-le-saunier": { lat: 46.677499, lng: 5.559875, label: "Lons-Le-Saunier" },
  "loon-plage": { lat: 50.989805, lng: 2.2362, label: "Loon-Plage" },
  "lorient": { lat: 47.750364, lng: -3.378025, label: "Lorient" },
  "los-angeles": { lat: 34.0522, lng: -118.2437, label: "Los Angeles (États-Unis)" },
  "ludon-medoc": { lat: 44.980575, lng: -0.598948, label: "Ludon-Médoc" },
  "ludres": { lat: 48.618012, lng: 6.177712, label: "Ludres" },
  "lure": { lat: 47.684245, lng: 6.496245, label: "Lure" },
  "luxembourg": { lat: 49.6116, lng: 6.1319, label: "Luxembourg (Luxembourg)" },
  "luxeuil-les-bains": { lat: 47.817813, lng: 6.374503, label: "Luxeuil-Les-Bains" },
  "lyon": { lat: 45.764, lng: 4.8357, label: "Lyon" },
  "madrid": { lat: 40.4168, lng: -3.7038, label: "Madrid (Espagne)" },
  "maizieres-les-metz": { lat: 49.212658, lng: 6.154495, label: "Maiziçres-Lçs-Metz" },
  "manosque": { lat: 43.826542, lng: 5.790238, label: "Manosque" },
  "marmande": { lat: 44.50184, lng: 0.170988, label: "Marmande" },
  "maromme": { lat: 49.475996, lng: 1.032172, label: "Maromme" },
  "marsannay-la-cote": { lat: 47.275243, lng: 5.003605, label: "Marsannay-La-Cçte" },
  "marseille": { lat: 43.2965, lng: 5.3698, label: "Marseille" },
  "martillac": { lat: 44.725144, lng: -0.554606, label: "Martillac" },
  "mauguio": { lat: 43.59327, lng: 3.995434, label: "Mauguio" },
  "maxeville": { lat: 48.707941, lng: 6.147492, label: "Maxçville" },
  "mazamet": { lat: 43.466271, lng: 2.370426, label: "Mazamet" },
  "meaux": { lat: 48.959287, lng: 2.902726, label: "Meaux" },
  "melun": { lat: 48.541332, lng: 2.655743, label: "Melun" },
  "menton": { lat: 43.7745, lng: 7.4975, label: "Menton" },
  "merignac": { lat: 44.83337, lng: -0.674682, label: "Mérignac" },
  "metz": { lat: 49.108385, lng: 6.194891, label: "Metz" },
  "meyzieu": { lat: 45.774559, lng: 5.008024, label: "Meyzieu" },
  "milan": { lat: 45.4642, lng: 9.19, label: "Milan (Italie)" },
  "mimizan": { lat: 44.195312, lng: -1.248112, label: "Mimizan" },
  "miramas": { lat: 43.582796, lng: 5.009776, label: "Miramas" },
  "mitry-mory": { lat: 48.963211, lng: 2.604405, label: "Mitry-Mory" },
  "monaco": { lat: 43.7384, lng: 7.4246, label: "Monaco" },
  "mondeville": { lat: 49.170017, lng: -0.310786, label: "Mondeville" },
  "mont-de-marsan": { lat: 43.891359, lng: -0.500182, label: "Mont-De-Marsan" },
  "montagny": { lat: 45.627934, lng: 4.753992, label: "Montagny" },
  "montagny-les-beaune": { lat: 46.99, lng: 4.85, label: "Montagny-lès-Beaune" },
  "montauban": { lat: 44.01984, lng: 1.363799, label: "Montauban" },
  "montereau-fault-yonne": { lat: 48.389786, lng: 2.957396, label: "Montereau-Fault-Yonne" },
  "montmorot": { lat: 46.681001, lng: 5.519497, label: "Montmorot" },
  "montpellier": { lat: 43.6108, lng: 3.8767, label: "Montpellier" },
  "montreal": { lat: 45.5017, lng: -73.5673, label: "Montréal (Canada)" },
  "montreuil": { lat: 48.863728, lng: 2.449364, label: "Montreuil" },
  "montrouge": { lat: 48.815929, lng: 2.316207, label: "Montrouge" },
  "morillon": { lat: 46.075602, lng: 6.672142, label: "Morillon" },
  "mougins": { lat: 43.6009, lng: 6.9634, label: "Mougins" },
  "moulin-les-metz": { lat: 49.095397, lng: 6.123362, label: "Moulins-lès-Metz" },
  "mulhouse": { lat: 47.751661, lng: 7.326517, label: "Mulhouse" },
  "munich": { lat: 48.1351, lng: 11.582, label: "Munich (Allemagne)" },
  "nancy": { lat: 48.688135, lng: 6.171263, label: "Nancy" },
  "nanterre": { lat: 48.898095, lng: 2.202314, label: "Nanterre" },
  "nantes": { lat: 47.2184, lng: -1.5536, label: "Nantes" },
  "neuilly-sur-marne": { lat: 48.864899, lng: 2.537373, label: "Neuilly-Sur-Marne" },
  "neuilly-sur-seine": { lat: 48.886191, lng: 2.265869, label: "Neuilly-Sur-Seine" },
  "neuville-aux-bois": { lat: 48.070025, lng: 2.052106, label: "Neuville-Aux-Bois" },
  "neuville-de-poitou": { lat: 46.679668, lng: 0.251724, label: "Neuville-De-Poitou" },
  "nevers": { lat: 46.988535, lng: 3.160778, label: "Nevers" },
  "new-york": { lat: 40.7128, lng: -74.006, label: "New York (États-Unis)" },
  "nice": { lat: 43.7102, lng: 7.262, label: "Nice" },
  "nimes": { lat: 43.814652, lng: 4.356289, label: "Nîmes" },
  "nogent-le-rotrou": { lat: 48.317471, lng: 0.808165, label: "Nogent-Le-Rotrou" },
  "noisiel": { lat: 48.847293, lng: 2.623401, label: "Noisiel" },
  "notre-dame-de-bondeville": { lat: 49.48484, lng: 1.055016, label: "Notre-Dame-De-Bondeville" },
  "olivet": { lat: 47.859196, lng: 1.889457, label: "Olivet" },
  "orleans": { lat: 47.873569, lng: 1.911358, label: "Orléans" },
  "ormoy": { lat: 48.572469, lng: 2.459533, label: "Ormoy" },
  "palaiseau": { lat: 48.716454, lng: 2.232499, label: "Palaiseau" },
  "pamiers": { lat: 43.128017, lng: 1.626781, label: "Pamiers" },
  "paris": { lat: 48.8566, lng: 2.3522, label: "Paris" },
  "paris-aubervilliers": { lat: 48.912878, lng: 2.386167, label: "Aubervilliers" },
  "paris-hq": { lat: 48.859, lng: 2.347, label: "Paris" },
  "paris-office": { lat: 48.859, lng: 2.347, label: "Paris" },
  "passy": { lat: 45.925787, lng: 6.703807, label: "Passy" },
  "pau": { lat: 43.313503, lng: -0.343106, label: "Pau" },
  "pauillac": { lat: 45.195143, lng: -0.769924, label: "Pauillac" },
  "peltre": { lat: 49.077308, lng: 6.229551, label: "Peltre" },
  "perigny": { lat: 46.161036, lng: -1.099583, label: "Périgny" },
  "perigueux": { lat: 45.193072, lng: 0.711299, label: "Périgueux" },
  "perpignan": { lat: 42.701507, lng: 2.902811, label: "Perpignan" },
  "pessac": { lat: 44.787468, lng: -0.675933, label: "Pessac" },
  "pierrelatte": { lat: 44.357315, lng: 4.689504, label: "Pierrelatte" },
  "plouhinec": { lat: 47.693989, lng: -3.24097, label: "Plouhinec" },
  "ploumagoar": { lat: 48.532016, lng: -3.114492, label: "Ploumagoar" },
  "pluneret": { lat: 47.680172, lng: -2.939465, label: "Pluneret" },
  "poissy": { lat: 48.930299, lng: 2.033457, label: "Poissy" },
  "poitiers": { lat: 46.586578, lng: 0.35668, label: "Poitiers" },
  "pontchateau": { lat: 47.441775, lng: -2.091299, label: "Pontchâteau" },
  "port-saint-louis-du-rhone": { lat: 43.399899, lng: 4.802233, label: "Port-Saint-Louis-du-Rhône" },
  "portes-les-valence": { lat: 44.876622, lng: 4.884414, label: "Portes-lès-Valence" },
  "portet-sur-garonne": { lat: 43.529131, lng: 1.396832, label: "Portet-Sur-Garonne" },
  "presles": { lat: 49.112925, lng: 2.286244, label: "Presles" },
  "pusignan": { lat: 45.754488, lng: 5.067288, label: "Pusignan" },
  "puteaux": { lat: 48.884156, lng: 2.237199, label: "Puteaux" },
  "quiberon": { lat: 47.486711, lng: -3.120228, label: "Quiberon" },
  "quimper": { lat: 47.998695, lng: -4.093228, label: "Quimper" },
  "quimperle": { lat: 47.861737, lng: -3.559902, label: "Quimperlç" },
  "rambouillet": { lat: 48.641966, lng: 1.844673, label: "Rambouillet" },
  "razac-sur-l-isle": { lat: 45.161992, lng: 0.617958, label: "Razac-Sur-L'Isle" },
  "reims": { lat: 49.250948, lng: 4.055595, label: "Reims" },
  "rennes": { lat: 48.1173, lng: -1.6778, label: "Rennes" },
  "rillieux-la-pape": { lat: 45.818387, lng: 4.892817, label: "Rillieux-La-Pape" },
  "riyadh": { lat: 24.7136, lng: 46.6753, label: "Riyadh (Arabie saoudite)" },
  "rochefort": { lat: 45.94403, lng: -0.967748, label: "Rochefort" },
  "rodez": { lat: 44.359272, lng: 2.566732, label: "Rodez" },
  "rognac": { lat: 43.496377, lng: 5.221441, label: "Rognac" },
  "roissy-en": { lat: 48.793178, lng: 2.655039, label: "Roissy-En-Brie" },
  "rome": { lat: 41.9028, lng: 12.4964, label: "Rome (Italie)" },
  "roncq": { lat: 50.745084, lng: 3.116387, label: "Roncq" },
  "rosselange": { lat: 49.257948, lng: 6.069269, label: "Rosselange" },
  "rouen": { lat: 49.440051, lng: 1.093912, label: "Rouen" },
  "rouxmesnil-bouteille": { lat: 49.895959, lng: 1.103015, label: "Rouxmesnil-Bouteilles" },
  "rungis": { lat: 48.749989, lng: 2.351473, label: "Rungis" },
  "saclay": { lat: 48.747821, lng: 2.165494, label: "Saclay" },
  "saint-aignan-grandlieu": { lat: 47.134973, lng: -1.616841, label: "Saint-Aignan-Grandlieu" },
  "saint-amand-montrond": { lat: 46.723917, lng: 2.522901, label: "Saint-Amand-Montrond" },
  "saint-aubain-de-medoc": { lat: 44.92419, lng: -0.737172, label: "Saint-Aubin-de-Médoc" },
  "saint-aubin-les-elbeuf": { lat: 49.302552, lng: 1.020026, label: "Saint-Aubin-lès-Elbeuf" },
  "saint-benoit": { lat: -21.061724, lng: 55.695202, label: "Saint-Benoît" },
  "saint-brice-courcelles": { lat: 49.266197, lng: 3.990229, label: "Saint-Brice-Courcelles" },
  "saint-brieuc": { lat: 48.508238, lng: -2.766074, label: "Saint-Brieuc" },
  "saint-chamond": { lat: 45.470463, lng: 4.505748, label: "Saint-Chamond" },
  "saint-cyr-sur-loire": { lat: 47.416945, lng: 0.657995, label: "Saint-Cyr-Sur-Loire" },
  "saint-denis": { lat: -20.909778, lng: 55.444588, label: "Saint-Denis" },
  "saint-dizier": { lat: 48.638926, lng: 4.957021, label: "Saint-Dizier" },
  "saint-etienne": { lat: 45.430195, lng: 4.370045, label: "Saint-Étienne" },
  "saint-etienne-du-rouvray": { lat: 49.385269, lng: 1.087904, label: "Saint-Étienne-du-Rouvray" },
  "saint-firmin": { lat: 46.846632, lng: 4.458717, label: "Saint-Firmin" },
  "saint-fons": { lat: 45.701914, lng: 4.855418, label: "Saint-Fons" },
  "saint-genis-pouilly": { lat: 46.256632, lng: 6.030166, label: "Saint-Genis-Pouilly" },
  "saint-gilles": { lat: 43.698432, lng: 4.411905, label: "Saint-Gilles" },
  "saint-herblain": { lat: 47.227082, lng: -1.625284, label: "Saint-Herblain" },
  "saint-laurent-du-var": { lat: 43.686846, lng: 7.18367, label: "Saint-Laurent-Du-Var" },
  "saint-leger-du-bourg-denis": { lat: 49.431512, lng: 1.154174, label: "Saint-Léger-du-Bourg-Denis" },
  "saint-malo": { lat: 48.642082, lng: -1.988626, label: "Saint-Malo" },
  "saint-mande": { lat: 48.841526, lng: 2.419441, label: "Saint-Mandé" },
  "saint-marcel": { lat: 46.775806, lng: 4.889732, label: "Saint-Marcel" },
  "saint-maurice": { lat: 48.817936, lng: 2.44166, label: "Saint-Maurice" },
  "saint-nazaire": { lat: 47.275247, lng: -2.242494, label: "Saint-Nazaire" },
  "saint-ouen": { lat: 47.82199, lng: 1.073394, label: "Saint-Ouen" },
  "saint-ouen-l-aumone": { lat: 49.047982, lng: 2.124065, label: "Saint-Ouen-l'Aumône" },
  "saint-ouen-sur-seine": { lat: 48.911696, lng: 2.333374, label: "Saint-Ouen-Sur-Seine" },
  "saint-parres-aux-tertres": { lat: 48.294602, lng: 4.119897, label: "Saint-Parres-Aux-Tertres" },
  "saint-paul-de-vence": { lat: 43.691717, lng: 7.117491, label: "Saint-Paul-De-Vence" },
  "saint-paul-les-durance": { lat: 43.691553, lng: 5.724929, label: "Saint-Paul-lès-Durance" },
  "saint-paul-lez-durance": { lat: 43.691553, lng: 5.724929, label: "Saint-Paul-lès-Durance" },
  "saint-pierre-la-garenne": { lat: 49.149993, lng: 1.396098, label: "Saint-Pierre-La-Garenne" },
  "saint-sauveur": { lat: 43.748312, lng: 1.402746, label: "Saint-Sauveur" },
  "saint-thegonnec-loc-eguiner": { lat: 48.499496, lng: -3.940535, label: "Saint-Thégonnec Loc-Eguiner" },
  "saint-vulbas": { lat: 45.834, lng: 5.293, label: "Saint-Vulbas (France)" },
  "sainte-maxime": { lat: 43.31927, lng: 6.635289, label: "Sainte-Maxime" },
  "san-francisco": { lat: 37.7749, lng: -122.4194, label: "San Francisco (États-Unis)" },
  "saran": { lat: 47.946923, lng: 1.875773, label: "Saran" },
  "sarge-les-le-mans": { lat: 48.040678, lng: 0.249355, label: "Sargé-lès-le-Mans" },
  "sarreguemines": { lat: 49.110922, lng: 7.07705, label: "Sarreguemines" },
  "sassenage": { lat: 45.214137, lng: 5.661988, label: "Sassenage" },
  "saverne": { lat: 48.739916, lng: 7.369676, label: "Saverne" },
  "schiltigheim": { lat: 48.611161, lng: 7.739943, label: "Schiltigheim" },
  "sedan": { lat: 49.698329, lng: 4.934086, label: "Sedan" },
  "semoy": { lat: 47.933346, lng: 1.952354, label: "Semoy" },
  "servon": { lat: 48.713549, lng: 2.592945, label: "Servon" },
  "seville": { lat: 49.596506, lng: 0.256405, label: "Hermeville" },
  "sevres": { lat: 48.819588, lng: 2.212003, label: "Sèvres" },
  "shah-alam": { lat: 3.0733, lng: 101.5185, label: "Shah Alam (Malaisie)" },
  "sillery": { lat: 49.196103, lng: 4.136894, label: "Sillery" },
  "singapore": { lat: 1.3521, lng: 103.8198, label: "Singapour" },
  "singapour": { lat: 1.3521, lng: 103.8198, label: "Singapour" },
  "six-fours-les-plages": { lat: 43.091706, lng: 5.8176, label: "Six-Fours-Les-Plages" },
  "soissons": { lat: 49.377401, lng: 3.327152, label: "Soissons" },
  "somain": { lat: 50.358485, lng: 3.277754, label: "Somain" },
  "sophia-antipolis": { lat: 43.6163, lng: 7.0553, label: "Sophia Antipolis" },
  "sotteville-les-rouen": { lat: 49.411721, lng: 1.093954, label: "Sotteville-lès-Rouen" },
  "souffelweyersheim": { lat: 48.630368, lng: 7.740028, label: "Souffelweyersheim" },
  "stockholm": { lat: 59.3293, lng: 18.0686, label: "Stockholm (Suède)" },
  "strasbourg": { lat: 48.5734, lng: 7.7521, label: "Strasbourg" },
  "subang-jaya": { lat: 3.0738, lng: 101.5861, label: "Subang Jaya (Malaisie)" },
  "sydney": { lat: 49.422621, lng: 4.101003, label: "Poilcourt-Sydney" },
  "taden": { lat: 48.484666, lng: -2.054247, label: "Taden" },
  "taguig": { lat: 14.535, lng: 121.0509, label: "Taguig (Philippines)" },
  "tarbes": { lat: 43.239349, lng: 0.06402, label: "Tarbes" },
  "taverny": { lat: 49.024195, lng: 2.212634, label: "Taverny" },
  "tergnier": { lat: 49.660693, lng: 3.298927, label: "Tergnier" },
  "terrasson-lavilledieu": { lat: 45.120657, lng: 1.304607, label: "Terrasson-Lavilledieu" },
  "thonon-les-bains": { lat: 46.3759, lng: 6.478152, label: "Thonon-Les-Bains" },
  "tokyo": { lat: 35.6762, lng: 139.6503, label: "Tokyo (Japon)" },
  "toronto": { lat: 43.6532, lng: -79.3832, label: "Toronto (Canada)" },
  "toul": { lat: 48.67803, lng: 5.900607, label: "Toul" },
  "toulon": { lat: 43.1242, lng: 5.928, label: "Toulon" },
  "toulouse": { lat: 43.6047, lng: 1.4442, label: "Toulouse" },
  "touques": { lat: 49.357601, lng: 0.111023, label: "Touques" },
  "tourcoing": { lat: 50.720797, lng: 3.157799, label: "Tourcoing" },
  "tours": { lat: 47.395476, lng: 0.695848, label: "Tours" },
  "trappes": { lat: 48.778249, lng: 1.993009, label: "Trappes" },
  "tremblay-en": { lat: 48.97725, lng: 2.55497, label: "Tremblay-En-France" },
  "tremuson": { lat: 48.525358, lng: -2.845427, label: "Trémuson" },
  "trevenans": { lat: 47.564434, lng: 6.863623, label: "Trévenans" },
  "troyes": { lat: 48.292817, lng: 4.075149, label: "Troyes" },
  "val-de-reuil": { lat: 49.261533, lng: 1.20933, label: "Val-De-Reuil" },
  "valbonne": { lat: 43.627339, lng: 7.016557, label: "Valbonne" },
  "valence": { lat: 44.920925, lng: 4.92297, label: "Valence" },
  "valenciennes": { lat: 50.358552, lng: 3.510438, label: "Valenciennes" },
  "vallauris": { lat: 43.574234, lng: 7.060116, label: "Vallauris" },
  "vannes": { lat: 47.659971, lng: -2.752192, label: "Vannes" },
  "vanves": { lat: 48.820966, lng: 2.286369, label: "Vanves" },
  "var": { lat: 43.5, lng: 6.3333, label: "Var (83)" },
  "vaucluse": { lat: 44.0, lng: 5.167, label: "Vaucluse (84)" },
  "vaulx-en-velin": { lat: 45.770799, lng: 4.923175, label: "Vaulx-En-Velin" },
  "vaux-le-penil": { lat: 48.528366, lng: 2.684421, label: "Vaux-le-Pénil" },
  "vendenheim": { lat: 48.669566, lng: 7.721357, label: "Vendenheim" },
  "vendin-le-vieil": { lat: 50.467754, lng: 2.859528, label: "Vendin-Le-Vieil" },
  "venelles": { lat: 43.592064, lng: 5.481118, label: "Venelles" },
  "venissieux": { lat: 45.707095, lng: 4.881379, label: "Vénissieux" },
  "verneuil-d-avre-et-d-iton": { lat: 48.758912, lng: 0.893475, label: "Verneuil D'Avre Et D'Iton" },
  "versailles": { lat: 48.802928, lng: 2.121128, label: "Versailles" },
  "vert-le-petit": { lat: 48.54835, lng: 2.36649, label: "Vert-Le-Petit" },
  "vienne": { lat: 45.526486, lng: 4.88366, label: "Vienne" },
  "vieux-thann": { lat: 47.802552, lng: 7.129313, label: "Vieux-Thann" },
  "ville-la-grand": { lat: 46.205587, lng: 6.257073, label: "Ville-La-Grand" },
  "villefranche-sur-saone": { lat: 45.985089, lng: 4.724382, label: "Villefranche-sur-Saône" },
  "villeneuve-d-ascq": { lat: 50.637788, lng: 3.147967, label: "Villeneuve-D'Ascq" },
  "villeneuve-la-garenne": { lat: 48.935658, lng: 2.324647, label: "Villeneuve-La-Garenne" },
  "villeneuve-les-beziers": { lat: 43.324569, lng: 3.280901, label: "Villeneuve-lès-Béziers" },
  "villeneuve-loubet": { lat: 43.639175, lng: 7.106505, label: "Villeneuve-Loubet" },
  "villetaneuse": { lat: 48.957593, lng: 2.343775, label: "Villetaneuse" },
  "villeurbanne": { lat: 45.768975, lng: 4.890035, label: "Villeurbanne" },
  "vincennes": { lat: 48.847279, lng: 2.437785, label: "Vincennes" },
  "viriat": { lat: 46.248528, lng: 5.227107, label: "Viriat" },
  "vitrolles": { lat: 43.443844, lng: 5.258646, label: "Vitrolles" },
  "vitry-le-francois": { lat: 48.726332, lng: 4.593002, label: "Vitry-le-François" },
  "vitry-sur-seine": { lat: 48.789495, lng: 2.39571, label: "Vitry-sur-Seine" },
  "voglans": { lat: 45.627331, lng: 5.890637, label: "Voglans" },
  "voreppe": { lat: 45.2884, lng: 5.624474, label: "Voreppe" },
  "voujeaucourt": { lat: 47.470263, lng: 6.782648, label: "Voujeaucourt" },
  "wambrechies": { lat: 50.695971, lng: 3.046954, label: "Wambrechies" },
  "wattrelos": { lat: 50.711887, lng: 3.218738, label: "Wattrelos" },
  "wittenheim": { lat: 47.814198, lng: 7.321897, label: "Wittenheim" },
  "wiwersheim": { lat: 48.639817, lng: 7.604437, label: "Wiwersheim" },
  "zurich": { lat: 47.3769, lng: 8.5417, label: "Zurich (Suisse)" },
};

export const PACA_CITY_SET = new Set(pacaCitySlugs as string[]);
// Ajouter les noms de départements et mots-clés régionaux (localisations non-ville)
[
  "alpes-de-haute-provence", "hautes-alpes", "alpes-maritimes",
  "bouches-du-rhone", "var", "vaucluse",
  "paca", "provence-alpes-cote-d-azur", "provence",
  "cote-d-azur", "sophia-antipolis", "sophia-antipolis-cedex",
  "le-canet", "cannet",
].forEach(s => PACA_CITY_SET.add(s));
export const PACA_DEPT_CODES = ["04", "05", "06", "13", "83", "84"];
export const PACA_DEPT_SET = new Set(PACA_DEPT_CODES);
export const PACA_DEPT_REGEXES = PACA_DEPT_CODES.map(dept => new RegExp(`\\b${dept}\\d{0,3}\\b`));
export const PACA_REGION_REGEXES = [
  /\bpaca\b/i,
  /\bprovence\b/i,
  /\bcôte d'azur\b/i,
  /\bcote d'azur\b/i,
  /\bsophia antipolis\b/i,
  /\bsophia-antipolis\b/i,
];

export const FRENCH_DEPARTMENTS_AND_REGIONS = new Set([
  "ain", "aisne", "allier", "alpes-de-haute-provence", "hautes-alpes", "alpes-maritimes", 
  "ardeche", "ardennes", "ariege", "aube", "aude", "aveyron", "bouches-du-rhone", 
  "calvados", "cantal", "charente", "charente-maritime", "cher", "correze", 
  "corse-du-sud", "haute-corse", "cote-d-or", "cotes-d-armor", "creuse", 
  "dordogne", "doubs", "drome", "eure", "eure-et-loir", "finistere", "gard", 
  "haute-garonne", "gers", "gironde", "herault", "ille-et-vilaine", "indre", 
  "indre-et-loire", "isere", "jura", "landes", "loir-et-cher", "loire", "haute-loire", 
  "loire-atlantique", "loiret", "lot", "lot-et-garonne", "lozere", "maine-et-loire", 
  "manche", "marne", "haute-marne", "mayenne", "meurthe-et-moselle", "meuse", 
  "morbihan", "moselle", "nievre", "nord", "oise", "orne", "pas-de-calais", 
  "puy-de-dome", "pyrenees-atlantiques", "hautes-pyrenees", "pyrenees-orientales", 
  "bas-rhin", "haut-rhin", "rhone", "haute-saone", "saone-et-loire", "sarthe", 
  "savoie", "haute-savoie", "paris", "seine-maritime", "seine-et-marne", "yvelines", 
  "deux-sevres", "somme", "tarn", "tarn-et-garonne", "var", "vaucluse", "vendee", 
  "vienne", "haute-vienne", "vosges", "yonne", "territoire-de-belfort", "essonne", 
  "hauts-de-seine", "seine-saint-denis", "val-de-marne", "val-d-oise",
  "guadeloupe", "martinique", "guyane", "la-reunion", "reunion", "mayotte",
  // Regions
  "auvergne-rhone-alpes", "bourgogne-franche-comte", "bretagne", "centre-val-de-loire", 
  "corse", "grand-est", "hauts-de-france", "ile-de-france", "normandie", 
  "nouvelle-aquitaine", "occitanie", "pays-de-la-loire", "provence-alpes-cote-d-azur", 
  "paca",
  // Other french indicators
  "france", "metropole", "tous-arrondissements", "proche", "region"
]);

export function isAbroadOffer(localisation: string): boolean {
  if (!localisation) return false;
  
  const locLower = localisation.toLowerCase();
  
  // Si la localisation contient des parenthèses
  const hasParentheses = localisation.includes("(") && localisation.includes(")");
  if (hasParentheses) {
    const match = localisation.match(/\(([^)]+)\)/);
    const parenContent = match ? match[1].trim() : "";
    const parenContentNorm = parenContent
      .toString()
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-+|-+$/g, "");
    
    // Si le contenu des parenthèses est un département ou code postal français (ex: "93", "75001"),
    // ou si la localisation désigne un territoire français d'outre-mer ou corse,
    // ou si c'est un département ou une région de France métropolitaine,
    // alors ce n'est PAS de l'étranger !
    const isFrenchDeptOrZip = /^\d+$/.test(parenContent) || /^[2][a-bA-B]$/.test(parenContent);
    const isFrenchTerritory = ["réunion", "reunion", "guadeloupe", "martinique", "guyane", "mayotte", "971", "972", "973", "974", "976", "corse"].some(d => locLower.includes(d));
    const isFrenchDeptOrRegionName = FRENCH_DEPARTMENTS_AND_REGIONS.has(parenContentNorm) || 
      Array.from(FRENCH_DEPARTMENTS_AND_REGIONS).some(item => parenContentNorm.includes(item));
    
    if (!isFrenchDeptOrZip && !isFrenchTerritory && !isFrenchDeptOrRegionName) {
      return true;
    }
  }

  // Autres vérifications par pays/villes célèbres
  const abroadCountries = [
    "allemagne", "royaume-uni", "etats-unis", "espagne", "italie", "suisse",
    "canada", "japon", "belgique", "pays-bas", "irlande", "luxembourg", "suède",
    "danemark", "norvège", "finlande", "autriche", "portugal", "pologne",
    "australie", "singapour", "chine", "inde", "brésil", "thaïlande", "thailande",
    "maroc", "tunisie", "sénégal", "senegal", "viêt nam", "vietnam", "mexique", 
    "argentine", "chili", "colombie", "pérou", "perou", "algérie", "algerie", 
    "côte d'ivoire", "cote d'ivoire", "cameroun", "madagascar", "liban", "turquie",
    "grèce", "grece", "roumanie", "hongrie", "tchéquie", "tchequie", "ukraine",
    "new york", "new-york", "los angeles", "london", "londres", "munich", "berlin", 
    "madrid", "barcelone", "barcelona", "rome", "milan", "stockholm", "geneve", "genève", 
    "zurich", "zürich", "montreal", "montréal", "toronto", "tokyo", "singapore", 
    "dubai", "dubaï", "bruxelles", "brussels", "dublin", "machelen", "bangpa-in", "bangkok",
    "fort mill", "union city", "rancho cordova", "san francisco", "boston", "washington", "chicago", "seattle", "austin",
    "étranger"
  ];
  return abroadCountries.some(country => locLower.includes(country));
}

export function isCoordinateInFrance(lat: number, lng: number): boolean {
  // 1. DROM-COM / DOM-TOM :
  // Réunion : lat ~ -21.1, lng ~ 55.5
  const isReunion = lat >= -21.5 && lat <= -20.8 && lng >= 55.2 && lng <= 55.9;
  if (isReunion) return true;

  // Martinique : lat ~ 14.6, lng ~ -61.0
  const isMartinique = lat >= 14.3 && lat <= 15.0 && lng >= -61.3 && lng <= -60.8;
  if (isMartinique) return true;

  // Guadeloupe : lat ~ 16.2, lng ~ -61.5
  const isGuadeloupe = lat >= 15.9 && lat <= 16.6 && lng >= -61.9 && lng <= -61.0;
  if (isGuadeloupe) return true;

  // Guyane : lat ~ 4.0, lng ~ -53.0
  const isGuyane = lat >= 2.0 && lat <= 6.0 && lng >= -54.5 && lng <= -51.5;
  if (isGuyane) return true;

  // Mayotte : lat ~ -12.8, lng ~ 45.1
  const isMayotte = lat >= -13.1 && lat <= -12.5 && lng >= 45.0 && lng <= 45.3;
  if (isMayotte) return true;

  // 2. France Métropolitaine :
  // Bounding box élargie : lat [41.0, 51.5], lng [-5.5, 10.0]
  // Mais nous devons EXCLURE la Suisse, la Belgique, l'Italie, etc. qui sont dans cette zone !
  const isInsideMetroFranceBox = lat >= 41.0 && lat <= 51.5 && lng >= -5.5 && lng <= 10.0;
  if (!isInsideMetroFranceBox) return false;

  // Exclure la Suisse : lat [45.8, 47.8], lng [5.9, 10.5]
  const isSwitzerland = lat >= 45.8 && lat <= 47.8 && lng >= 5.9 && lng <= 10.5;
  if (isSwitzerland) return false;

  // Exclure la Belgique : lat [49.5, 51.5], lng [2.5, 6.4]
  const isBelgium = lat >= 49.5 && lat <= 51.5 && lng >= 2.5 && lng <= 6.4;
  if (isBelgium) return false;

  // Exclure le Luxembourg : lat [49.4, 50.2], lng [5.7, 6.6]
  const isLuxembourg = lat >= 49.4 && lat <= 50.2 && lng >= 5.7 && lng <= 6.6;
  if (isLuxembourg) return false;

  // Exclure l'Italie du Nord (ex: Milan) : lat [44.0, 47.0], lng [6.6, 10.0]
  const isNorthItaly = lat >= 44.0 && lat <= 47.0 && lng >= 6.6 && lng <= 10.0;
  if (isNorthItaly) return false;

  // Exclure Monaco : lat [43.72, 43.76], lng [7.40, 7.45]
  const isMonaco = lat >= 43.72 && lat <= 43.76 && lng >= 7.40 && lng <= 7.45;
  if (isMonaco) return false;

  // Exclure l'Andorre : lat [42.4, 42.7], lng [1.4, 1.8]
  const isAndorra = lat >= 42.4 && lat <= 42.7 && lng >= 1.4 && lng <= 1.8;
  if (isAndorra) return false;

  // Exclure l'Espagne du Nord (frontière pyrénéenne) : lat < 42.3 et lng < 3.2
  const isSpain = lat < 42.3 && lng < 3.2;
  if (isSpain) return false;

  return true;
}

export function checkIsAbroad(localisation: string, geo: { lat: number; lng: number } | null): boolean {
  if (!localisation) return false;
  const locLower = localisation.toLowerCase();
  
  // RÈGLE D'OR : Si la localisation a des parenthèses et n'est pas un DROM-COM ni un département français (ex: "Lausanne (Suisse)" vs "Aubervilliers (93)")
  // c'est de l'étranger à 100% de manière absolue.
  const hasParentheses = localisation.includes("(") && localisation.includes(")");
  const match = localisation.match(/\(([^)]+)\)/);
  const parenContent = match ? match[1].trim() : "";
  const parenContentNorm = parenContent
    .toString()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
    
  const isFrenchDeptOrZip = /^\d+$/.test(parenContent) || /^[2][a-bA-B]$/.test(parenContent);
  const isFrenchTerritory = ["réunion", "reunion", "guadeloupe", "martinique", "guyane", "mayotte", "971", "972", "973", "974", "976", "corse"].some(d => locLower.includes(d));
  const isFrenchDeptOrRegionName = FRENCH_DEPARTMENTS_AND_REGIONS.has(parenContentNorm) || 
    Array.from(FRENCH_DEPARTMENTS_AND_REGIONS).some(item => parenContentNorm.includes(item));
  
  if (hasParentheses && !isFrenchDeptOrZip && !isFrenchTerritory && !isFrenchDeptOrRegionName) {
    return true;
  }

  let isAbroad = isAbroadOffer(localisation);
  if (geo) {
    // Si c'est à Lille, Modane ou Nice (sans parenthèses et sans mot de pays étranger dans le texte),
    // on force isAbroad à false pour éviter les faux-positifs des bounding boxes de frontières.
    const hasAbroadKeyword = isAbroadOffer(localisation);
    const hasFrenchParentheses = hasParentheses && (isFrenchDeptOrZip || isFrenchTerritory || isFrenchDeptOrRegionName);
    
    if ((!hasParentheses || hasFrenchParentheses) && !hasAbroadKeyword) {
      isAbroad = false;
    } else {
      isAbroad = !isCoordinateInFrance(geo.lat, geo.lng);
    }
  }
  return isAbroad;
}




export function cleanCityName(loc: string): string {
  if (!loc) return "";
  let clean = loc.toLowerCase().trim();
  // Remplacer les abréviations "st" par "saint" pour uniformité
  clean = clean.replace(/\bst\b/g, "saint");
  // Retirer tout ce qui est entre parenthèses, comme le département, ex: "Brest (29)" -> "Brest"
  clean = clean.replace(/\s*\([^)]*\)\s*/g, "");
  // Retirer les codes postaux seuls à la fin (5 chiffres), ex: "Brest 29200" -> "Brest"
  clean = clean.replace(/\s*\b\d{5}\b\s*/g, "");
  // Retirer les mentions de pays "france", "monaco"
  clean = clean.replace(/,\s*(france|monaco)/gi, "");
  return clean.trim();
}

export function slugify(text: string): string {
  return text
    .toString()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getStandardCityKey(loc: string, geographyMap: { [key: string]: any }): string | null {
  if (!loc) return null;
  
  const cleaned = cleanCityName(loc);
  const slug = slugify(cleaned);
  
  // 1. Correspondance exacte sur le slug
  if (geographyMap[slug]) {
    return slug;
  }
  
  // 2. Correspondance intelligente par mot entier pour éviter les collisions de sous-chaînes (ex: Vincennes/Cannes, Lillebonne/Lille)
  const GEOGRAPHIC_STOPWORDS = new Set([
    "mer", "port", "var", "vares", "val", "sur", "les", "de", "la", "le", "en", "sous", "aux", "au", "des", "du", "d", "l", "sainte", "saint", "un", "une", "et", "a",
    "union", "fort", "new", "san", "santa", "city", "town"
  ]);
  const locWords = slug.split("-").filter(Boolean);
  
  for (const key of Object.keys(geographyMap)) {
    const keyWords = key.split("-").filter(Boolean);
    
    if (keyWords.length > 1) {
      // Pour une clé multi-mots (ex: "sophia-antipolis"), tous les mots de la clé doivent être présents
      if (keyWords.every(word => locWords.includes(word))) {
        return key;
      }
    } else if (keyWords.length === 1) {
      // Si la clé unique est un mot géographique courant, on évite de le faire correspondre à un nom composé
      if (locWords.length > 1 && GEOGRAPHIC_STOPWORDS.has(keyWords[0])) {
        continue;
      }
      // Pour une clé à mot unique (ex: "cannes"), le mot doit figurer de façon isolée (pas "vincennes")
      if (locWords.includes(keyWords[0])) {
        return key;
      }
    }
  }

  return null;
}

