"""Parametres statiques de la collecte des sources legales."""

DOMAINES_A_LANCER = [
    "SD",
    "RT",
    "QLIO",
    "CS",
    "GEA",
    "INFOCOM",
    "INFO",
    "TC",
    "GEII",
]

# Ordre des feuilles Excel et des sources attendues par la fusion.
SOURCE_NAMES = [
    "France Travail API",
    "La Bonne Alternance",
    "PASS Fonction publique",
    "CEA Emploi RSS",
    "Orange Jobs",
    "Thales Careers",
    "Capgemini Careers",
    "SNCF Recrutement",
]

# Sources lancees par defaut : uniquement celles avec API/RSS public stable.
DEFAULT_ENABLED_SOURCES = {
    "France Travail API",
    "La Bonne Alternance",
    "PASS Fonction publique",
    "CEA Emploi RSS",
}

# Valeurs par defaut surchargeables via variables d'environnement GitHub Actions.
DEFAULT_LBA_API_URL = "https://api.apprentissage.beta.gouv.fr/api/job/v1/export"
DEFAULT_LBA_RADIUS = "100"
DEFAULT_LBA_CALLER = "IUTSOPHIAOffresEtudiant"
DEFAULT_FRANCE_TRAVAIL_PAGE_SIZE = 150
DEFAULT_FRANCE_TRAVAIL_MAX_RESULTS = 900
DEFAULT_FRANCE_TRAVAIL_STAGE_MAX_RESULTS = 900
DEFAULT_FRANCE_TRAVAIL_DETAIL_LIMIT = 300
DEFAULT_FRANCE_TRAVAIL_DETAIL_DELAY = 0.03
DEFAULT_FRANCE_TRAVAIL_LINK_DURATION_LIMIT = 700
DEFAULT_FRANCE_TRAVAIL_LINK_DURATION_DELAY = 0.03
DEFAULT_LBA_LINK_COMPANY_LIMIT = 700
DEFAULT_LBA_LINK_COMPANY_DELAY = 0.05
DEFAULT_LBA_DETAIL_LIMIT = 800
DEFAULT_LBA_DETAIL_DELAY = 0.03
STUDENT_CONTRACTS = {"Stage", "Alternance"}

# Codes ROME utilises pour elargir les recherches France Travail et LBA par domaine.
DOMAIN_ROMES = {
    "SD": [
        "H1215",
        "H1501",
        "K1906",
        "M1201",
        "M1403",
        "M1404",
        "M1405",
        "M1411",
        "M1414",
        "M1806",
        "M1811",
        "M1824",
        "M1851",
        "M1856",
        "M1863",
        "H1531",
        "H1534",
        "M1419",
        "M1420",
        "M1421",
        "M1422",
        "M1423",
        "M1424",
        "M1425",
        "M1426",
        "M1868",
        "M1872",
        "M1873",
        "M1888",
        "M1889",
        "M1890",
        "M1891",
        "M1893",
        "M1894",
    ],
    "RT": [
        "I1305",
        "I1307",
        "M1801",
        "M1802",
        "M1804",
        "M1805",
        "M1806",
        "M1810",
        "M1811",
    ],
    "QLIO": [
        "H1401",
        "H1402",
        "H1403",
        "H1404",
        "H1502",
        "H1506",
        "H2502",
        "H2503",
        "M1101",
        "M1102",
        "N1301",
        "N1302",
        "N1303",
    ],
    "CS": [
        "K1201",
        "K1202",
        "K1203",
        "K1204",
        "K1205",
        "K1206",
        "K1207",
        "K1301",
        "K1302",
        "K1303",
        "K1403",
        "K1801",
    ],
    "GEA": [
        "M1101",
        "M1102",
        "M1201",
        "M1202",
        "M1203",
        "M1204",
        "M1205",
        "M1501",
        "M1502",
        "M1503",
        "M1604",
        "M1605",
        "M1607",
        "M1608",
    ],
    "INFOCOM": [
        "E1103",
        "E1104",
        "E1106",
        "E1107",
        "E1205",
        "E1401",
        "E1402",
        "M1403",
        "M1704",
        "M1705",
        "M1707",
    ],
    "INFO": [
        "M1801",
        "M1802",
        "M1805",
        "M1806",
        "M1810",
        "M1811",
        "M1824",
        "M1851",
        "M1856",
        "M1863",
        "M1868",
    ],
    "TC": [
        "D1401",
        "D1402",
        "D1403",
        "D1404",
        "D1406",
        "D1501",
        "M1701",
        "M1702",
        "M1703",
        "M1704",
        "M1705",
        "M1706",
        "M1707",
    ],
    "GEII": [
        "H1202",
        "H1206",
        "H1208",
        "H1209",
        "H1504",
        "I1302",
        "I1304",
        "M1805",
        "M1810",
    ],
}

LBA_JOB_NAMES = {
    "SD": "Analyse de donnees, data",
    "RT": "reseaux telecom, cybersecurite",
    "QLIO": "qualite logistique industrielle organisation, supply chain",
    "CS": "carrieres sociales, intervention sociale",
    "GEA": "gestion des entreprises, comptabilite, ressources humaines",
    "INFOCOM": "information communication, communication digitale",
    "INFO": "informatique, developpeur web, developpeur logiciel",
    "TC": "techniques de commercialisation, commercial, marketing",
    "GEII": "electronique, electrotechnique, automatisme, informatique industrielle",
}

# Mots-cles de validation metier pour filtrer les sources trop larges.
TITLE_DOMAIN_KEYWORDS = {
    "SD": [
        "data",
        "donnees",
        "statistique",
        "biostatistique",
        "machine learning",
        "intelligence artificielle",
        "analyse de donnees",
        "ai",
        "ia",
        "analytics",
        "bi",
        "scientist",
    ],
    "RT": [
        "network",
        "telecom",
        "telecommunications",
        "cybersecurite",
        "intrusion",
        "infrastructure",
        "hpc",
        "stockage",
        "cloud",
        "securite informatique",
        "reseau informatique",
        "reseau",
        "reseaux",
        "sysadmin",
        "systeme",
        "systemes",
        "devops",
        "sre",
        "cyber",
    ],
    "QLIO": [
        "qualite",
        "logistique",
        "supply chain",
        "production",
        "amelioration continue",
        "methodes",
        "industrialisation",
        "environnement",
        "approvisionnement",
        "stocks",
        "planning",
        "planification",
        "ordonnancement",
        "lean",
        "qse",
        "hse",
    ],
    "CS": [
        "social",
        "animation",
        "intervention sociale",
        "educateur",
        "mediation",
        "accompagnement",
        "carrieres sociales",
        "insertion",
        "aide",
        "communaute",
    ],
    "GEA": [
        "comptabilite",
        "finance",
        "ressources humaines",
        "controle de gestion",
        "budget",
        "paie",
        "achats",
        "gestion",
        "rh",
        "talent",
        "recruiting",
        "recrutement",
        "law",
        "legal",
        "juriste",
        "comptable",
        "people",
        "office manager",
        "audit",
        "administratif",
    ],
    "INFOCOM": [
        "communication",
        "journalisme",
        "editorial",
        "redaction",
        "newsletter",
        "evenementiel",
        "contenu",
        "charge de communication",
        "chargee de communication",
        "digital",
        "social media",
        "community manager",
        "media",
        "content",
        "creator",
        "video",
        "graphiste",
        "designer",
        "ui",
        "ux",
    ],
    "INFO": [
        "informatique",
        "developpement",
        "logiciel",
        "web",
        "application",
        "python",
        "java",
        "developpeur",
        "developer",
        "engineer",
        "fullstack",
        "backend",
        "frontend",
        "dev",
        "tech",
        "it",
        "javascript",
        "typescript",
        "c++",
        "c#",
        "php",
        "mobile",
        "product manager",
    ],
    "TC": [
        "commercial",
        "commerce",
        "vente",
        "marketing",
        "business developer",
        "relation client",
        "account manager",
        "business development",
        "vendeur",
        "technico",
        "sales",
        "bizdev",
        "bdr",
        "sdr",
        "customer",
        "growth",
        "grow",
    ],
    "GEII": [
        "electronique",
        "électronique",
        "electrotechnique",
        "électrotechnique",
        "automatisme",
        "automates",
        "systemes embarques",
        "systèmes embarqués",
        "informatique industrielle",
        "genie electrique",
        "génie électrique",
        "geii",
        "robotique",
        "hardware",
        "iot",
        "cablage",
        "fpga",
        "microcontroleur",
    ],
}

RSS_SOURCES = {
    "CEA Emploi RSS": [
        "https://www.emploi.cea.fr/handlers/offerRss.ashx?LCID=1036",
        "https://www.emploi.cea.fr/handlers/offerRss.ashx?LCID=1036&Rss_Contract=1292",
        "https://www.emploi.cea.fr/handlers/offerRss.ashx?LCID=1036&Rss_Contract=579",
    ],
}

SMARTRECRUITERS_SOURCES = {}

# Sources referencees mais desactivees tant qu'aucun endpoint officiel stable n'est fourni.
MANUAL_API_SOURCES = {
    "Orange Jobs": {
        "url": "https://jobs.orange.com/jobs/v3/search",
        "enabled": False,
        "reason": "Le portail public Orange Jobs ne fournit pas d'API/RSS documenté dans le dépôt.",
    },
    "Capgemini Careers": {
        "url": "https://careers.capgemini.com",
        "enabled": False,
        "reason": "Le portail Capgemini est conservé comme source à configurer quand un endpoint officiel est fourni.",
    },
    "EDF Enedis RTE": {
        "url": "https://www.edf.fr/edf-recrute",
        "enabled": False,
        "reason": "EDF/Enedis/RTE utilisent plusieurs portails ; aucun endpoint commun officiel n'est configuré.",
    },
    "Naval Group Careers": {
        "url": "https://www.naval-group.com/fr/carrieres",
        "enabled": False,
        "reason": "Le portail est listé, sans endpoint API/RSS public configuré.",
    },
    "SNCF Recrutement": {
        "url": "https://emploi.sncf.com",
        "enabled": False,
        "reason": "Le portail est listé, sans endpoint API/RSS public configuré.",
    },
}
