# config.py

# Dictionnaire de référence des formulations de diplômes par niveau d'études
SHARED_STUDIES = {
    "Bac+2": [
        "bac+2",
        "bts",
        "dut",
        "deug",
        "technicien supérieur",
        "technicien superieur",
    ],
    "Bac+3": [
        "bac+3",
        "licence",
        "licence professionnelle",
        "bachelor",
        "b.u.t.",
    ],
    "Bac+4": [
        "bac+4",
        "master 1",
        "m1",
    ],
    "Bac+5": [
        "bac+5",
        "master",
        "master 2",
        "m2",
        "école d'ingénieur",
        "ecole d'ingenieur",
        "ingénieur",
        "ingenieur",
    ],
}


def build_etudes(but_name, but_keywords, levels=[2, 3, 4, 5]):
    """
    Construit de manière dynamique le dictionnaire des études d'un département
    en injectant les expressions de diplômes partagées.
    """
    etudes = {but_name: but_keywords}
    for lvl in levels:
        key = f"Bac+{lvl}"
        if key in SHARED_STUDIES:
            etudes[key] = SHARED_STUDIES[key]
    return etudes


# CONFIGURATION DES DOMAINES
CONFIGS = {
    "SD": {
        "nom_export": "sd",
        "keywords": [
            "Analyse de donnees",
            "data",
            "science des données",
            "statistiques",
            "analyst",
        ],
        "etudes": build_etudes(
            "BUT Science des données",
            [
                "but science des données",
                "but sd",
                "science des données",
                "statistique et informatique décisionnelle",
                "stid",
            ],
            levels=[2, 3, 4, 5],
        ),
        "competences": {
            "Python": ["python"],
            "SQL": [
                "sql",
                "mysql",
                "postgresql",
                "postgres",
                "oracle sql",
                "sql server",
            ],
            "Excel": ["excel", "vba", "tableur", "formules complexes", "macro"],
            "Power BI": ["power bi", "powerbi"],
            "Tableau": ["tableau", "tableau software"],
            "Data visualisation": [
                "dataviz",
                "data visualisation",
                "visualisation de données",
                "visualisation des données",
                "dashboard",
                "tableau de bord",
            ],
            "Machine Learning": [
                "machine learning",
                "ml",
                "modèle prédictif",
                "modele predictif",
                "apprentissage automatique",
            ],
            "IA": [
                "intelligence artificielle",
                "ia",
                "ai",
                "generative ai",
                "ia générative",
                "ia generative",
            ],
            "Statistiques": [
                "statistique",
                "statistiques",
                "analyse statistique",
                "probabilités",
                "probabilites",
            ],
            "R": ["langage r", " r ", "r studio", "rstudio"],
            "ETL": [
                "etl",
                "talend",
                "informatica",
                "data pipeline",
                "pipeline de données",
            ],
            "Big Data": ["big data", "spark", "hadoop", "databricks"],
            "Cloud": ["aws", "azure", "gcp", "google cloud", "cloud"],
            "Pandas": ["pandas", "numpy", "scikit-learn", "sklearn"],
            "DataViz alternatives": [
                "looker",
                "looker studio",
                "metabase",
                "knime",
                "dbt",
                "clickhouse",
                "matplotlib",
                "seaborn",
                "sas",
                "spss",
            ],
        },
    },
    "RT": {
        "nom_export": "reseaux_telecom",
        "keywords": [
            "réseaux",
            "télécommunications",
            "télécoms",
            "administrateur réseaux",
            "technicien réseaux",
            "infrastructure réseaux",
            "systèmes et réseaux",
            "support réseaux",
            "cybersécurité réseaux",
        ],
        "etudes": build_etudes(
            "BUT Réseaux & Télécommunications",
            [
                "but réseaux et télécommunications",
                "but reseaux et telecommunications",
                "but r&t",
                "but rt",
                "réseaux et télécommunications",
                "reseaux et telecommunications",
            ],
            levels=[2, 3, 4, 5],
        ),
        "competences": {
            "Réseaux": ["network", "networking", "lan", "wan", "ethernet", "ip"],
            "Télécommunications": [
                "télécom",
                "télécoms",
                "telecom",
                "telecoms",
                "télécommunications",
                "telecommunications",
            ],
            "Cisco": ["cisco", "ccna", "ccnp"],
            "TCP/IP": ["tcp/ip", "tcp ip", "adresse ip", "protocole ip", "adressage ip"],
            "LAN / WAN": ["lan", "wan", "wlan"],
            "VLAN": ["vlan", "vlans"],
            "Routage / Switching": [
                "routage",
                "routing",
                "switch",
                "switching",
                "routeur",
                "commutateur",
            ],
            "Firewall": [
                "firewall",
                "pare-feu",
                "palo alto",
                "fortinet",
                "fortigate",
                "stormshield",
            ],
            "Cybersécurité": [
                "cybersécurité",
                "cybersecurite",
                "cyber",
                "sécurité informatique",
                "securite informatique",
                "sécurité réseau",
                "securite reseau",
            ],
            "Linux": ["linux", "ubuntu", "debian", "redhat", "centos"],
            "Windows Server": [
                "windows server",
                "active directory",
                "ad",
                "powershell",
            ],
            "Supervision": [
                "supervision",
                "monitoring",
                "zabbix",
                "nagios",
                "grafana",
            ],
            "Virtualisation": ["virtualisation", "vmware", "hyper-v", "proxmox"],
            "VoIP / ToIP": ["voip", "toip", "sip", "téléphonie ip", "telephonie ip"],
            "Fibre optique": ["raccordement fibre", "fibre optique", "ftth", "ftto"],
            "Wi-Fi": ["wifi", "wi-fi", "wireless"],
            "5G / Radio": ["5g", "radio", "antenne", "réseau mobile", "reseau mobile"],
            "Cloud Infrastructure": ["aws", "azure", "cloud computing", "gcp"],
            "Sécurité et VPN": ["vpn", "ipsec", "cryptographie", "test d'intrusion", "sso"],
            "Scripting": ["python", "bash", "shell"],
        },
    },
    "QLIO": {
        "nom_export": "qlio",
        "keywords": [
            "qualite logistique industrielle organisation",
            "supply chain",
            "amelioration continue",
            "gestion de production",
        ],
        "etudes": build_etudes(
            "BUT QLIO",
            [
                "but qlio",
                "qualité logistique industrielle et organisation",
                "qualite logistique industrielle et organisation",
                "qlio",
            ],
            levels=[2, 3, 4, 5],
        ),
        "competences": {
            "Logistique": [
                "logistique",
                "logistics",
                "flux logistique",
                "chaine logistique",
                "chaîne logistique",
            ],
            "Supply Chain": [
                "supply chain",
                "supply-chain",
                "chaîne d'approvisionnement",
                "chaine d'approvisionnement",
            ],
            "Approvisionnement": [
                "approvisionnement",
                "approvisionnements",
                "procurement",
                "achat",
                "achats",
            ],
            "Gestion des stocks": [
                "stock",
                "stocks",
                "gestion des stocks",
                "inventaire",
                "inventory",
            ],
            "Planification": [
                "planification",
                "planning",
                "prévision",
                "prevision",
                "forecast",
            ],
            "Ordonnancement": [
                "ordonnancement",
                "planification de production",
                "planning production",
            ],
            "Production": [
                "production",
                "gestion de production",
                "atelier",
                "ligne de production",
            ],
            "Qualité": [
                "qualité",
                "qualite",
                "contrôle qualité",
                "controle qualite",
                "assurance qualité",
                "assurance qualite",
            ],
            "Amélioration continue": [
                "amélioration continue",
                "amelioration continue",
                "continuous improvement",
                "kaizen",
            ],
            "Lean": ["lean", "lean management", "lean manufacturing", "5s", "six sigma"],
            "Méthodes industrielles": [
                "méthodes",
                "methodes",
                "méthodes industrielles",
                "methodes industrielles",
                "industrialisation",
            ],
            "QSE / HSE": [
                "qse",
                "hse",
                "sécurité environnement",
                "securite environnement",
                "qualité sécurité environnement",
                "qualite securite environnement",
            ],
            "ERP": ["erp", "sap", "oracle", "sage"],
            "KPI": [
                "kpi",
                "indicateur",
                "indicateurs",
                "tableau de bord",
                "performance",
            ],
            "Excel": ["excel", "vba", "tableur"],
            "Normes et Audit": [
                "iso 9001",
                "iso 14001",
                "audit qualité",
                "conformité",
                "normes",
            ],
            "Transport et Flux": [
                "transport",
                "affrètement",
                "logistique de distribution",
                "incoterms",
            ],
        },
    },
    "CS": {
        "nom_export": "cs",
        "keywords": [
            "carrières sociales",
            "animation sociale",
            "intervention sociale",
            "assistant social",
            "éducateur spécialisé",
            "animateur social",
            "action sociale",
            "travailleur social",
            "accompagnement social",
            "médiateur social",
        ],
        "etudes": build_etudes(
            "BUT Carrières Sociales",
            ["but carrières sociales", "but carrieres sociales", "carrières sociales", "carrieres sociales"],
            levels=[2, 3],
        ),
        "competences": {
            "Accompagnement social": [
                "accompagnement social",
                "action sociale",
                "intervention sociale",
                "travail social",
            ],
            "Animation": [
                "animation",
                "animateur",
                "animatrice",
                "projet d'animation",
                "animation socioculturelle",
                "animateur socioculturel",
                "animation du cadre de vie",
                "coordination d'activités",
            ],
            "Médiation": [
                "médiation",
                "mediation",
                "relation usager",
                "public fragile",
                "publics fragiles",
            ],
            "Gestion de projet": [
                "gestion de projet",
                "coordination sociale",
                "coordination de projet social",
                "pilotage de projet social",
                "gestion d'équipements",
                "mise en œuvre de projets",
                "conception de projet",
                "cadre intermédiaire",
                "coordination d'activités socioculturelles",
            ],
            "Communication sociale": [
                "rédaction",
                "redaction",
                "sensibilisation",
                "accompagnement social",
            ],
            "Insertion et Publics": [
                "insertion professionnelle",
                "insertion sociale",
                "protection de l'enfance",
                "logement social",
                "hébergement d'urgence",
                "precarite",
                "précarité",
                "personnes âgées",
                "personnes agees",
                "personnes en situation de handicap",
                "situation de handicap",
            ],
            "Méthodes de terrain": [
                "écoute active",
                "ecoute active",
                "entretien individuel",
                "entretien semi-directif",
                "diagnostic territorial",
            ],
        },
        "semantic_threshold": 0.45,
    },
    "GEA": {
        "nom_export": "gea",
        "keywords": [
            "gestion des entreprises",
            "comptabilite",
            "ressources humaines",
            "finance",
            "gestion administrative",
        ],
        "etudes": build_etudes(
            "BUT GEA",
            [
                "but gea",
                "gestion des entreprises et des administrations",
                "gestion entreprises administrations",
                "gea",
            ],
            levels=[2, 3, 5],
        ),
        "competences": {
            "Comptabilité": [
                "comptabilité",
                "comptabilite",
                "facturation",
                "bilan",
                "compta",
                "saisie comptable",
                "lettrage",
                "rapprochement bancaire",
                "tva",
                "déclaration de tva",
            ],
            "Contrôle de gestion": [
                "contrôle de gestion",
                "controle de gestion",
                "budget",
                "reporting",
                "kpi",
                "dashboards",
                "analyse de rentabilité",
                "rentabilité",
                "écart",
                "analyse des écarts",
                "costing",
            ],
            "Ressources humaines": [
                "ressources humaines",
                "rh",
                "paie",
                "recrutement",
                "administration du personnel",
                "gadz",
                "dpae",
                "contrat de travail",
                "gestion des temps",
                "absences",
            ],
            "Gestion administrative": [
                "gestion administrative",
                "administratif",
                "administration",
                "archivage",
                "secrétariat",
                "secretariat",
                "accueil téléphonique",
                "courrier",
                "devis",
                "factures",
            ],
            "Excel": ["excel", "vba", "tableur"],
            "Logiciels de Gestion": [
                "sage",
                "cegid",
                "sap",
                "silae",
                "lucca",
                "odoo",
                "quickbooks",
                "ebp",
                "quadra",
                "ibiza",
                "pennylane",
                "adp",
            ],
        },
    },
    "INFOCOM": {
        "nom_export": "infocom",
        "keywords": [
            "information communication",
            "communication digitale",
            "community manager",
            "communication digital",
            "marketing digital",
        ],
        "etudes": build_etudes(
            "BUT Information-Communication",
            [
                "but information communication",
                "but info com",
                "but infocom",
                "information communication",
                "info-com",
                "infocom",
            ],
            levels=[2, 3],
        ),
        "competences": {
            "Communication digitale": [
                "communication digitale",
                "digital communication",
                "réseaux sociaux",
                "reseaux sociaux",
                "social media",
                "infographie",
                "storytelling",
                "brand content",
            ],
            "Community management": [
                "community manager",
                "community management",
                "animation de communauté",
                "animation de communaute",
                "modération",
                "moderation",
                "planning editorial",
                "influenceur",
            ],
            "Rédaction": [
                "rédaction",
                "redaction",
                "copywriting",
                "contenu éditorial",
                "contenu editorial",
                "relecture",
                "synthese",
                "charte editoriale",
            ],
            "Marketing": [
                "marketing",
                "campagne",
                "seo",
                "newsletter",
                "e-mailing",
                "growth hacking",
                "lead generation",
            ],
            "PAO": [
                "canva",
                "photoshop",
                "indesign",
                "illustrator",
                "creative suite",
                "adobe cc",
            ],
            "CMS et Web": [
                "wordpress",
                "wix",
                "webflow",
                "prestashop",
                "shopify",
                "drupal",
                "joomla",
            ],
            "Création visuelle et vidéo": [
                "premiere pro",
                "montage video",
                "figma",
                "ui",
                "ux",
                "création de contenu",
                "after effects",
                "capcut",
                "motion design",
            ],
            "Webmarketing et Analyse": [
                "google analytics",
                "sea",
                "adwords",
                "webmarketing",
                "semrush",
                "google ads",
                "conversion rate",
                "kpi",
            ],
        },
    },
    "INFO": {
        "nom_export": "info",
        "keywords": [
            "informatique",
            "developpeur web",
            "developpeur logiciel",
            "programmation",
            "dev",
        ],
        "etudes": build_etudes(
            "BUT Informatique",
            ["but informatique", "informatique", "développement logiciel", "developpement logiciel"],
            levels=[2, 3, 5],
        ),
        "competences": {
            "Python": [
                "python",
                "django",
                "flask",
                "fastapi",
            ],
            "Java": [
                "java",
                "spring",
                "spring boot",
                "maven",
                "gradle",
                "hibernate",
            ],
            "JavaScript": [
                "javascript",
                "typescript",
                "react",
                "node",
                "vue",
                "angular",
                "next.js",
                "nextjs",
                "express",
                "nestjs",
                "npm",
                "yarn",
                "pnpm",
            ],
            "Web": [
                "html",
                "css",
                "api",
                "rest",
                "rest api",
                "graphql",
                "tailwind",
                "bootstrap",
                "sass",
            ],
            "SQL": [
                "sql",
                "mysql",
                "postgresql",
                "oracle sql",
                "sqlite",
                "mariadb",
                "nosql",
                "dbms",
                "sgbd",
            ],
            "DevOps": [
                "git",
                "docker",
                "ci/cd",
                "devops",
                "github",
                "gitlab",
                "docker-compose",
            ],
            "Systèmes": [
                "linux",
                "windows server",
                "administration système",
                "administration systeme",
                "bash",
                "powershell",
                "active directory",
                "virtualisation",
            ],
            "Mobile": [
                "mobile",
                "swift",
                "kotlin",
                "flutter",
                "react native",
                "ios",
                "android",
                "swiftui",
                "jetpack compose",
                "expo",
            ],
            "Base de données NoSQL": [
                "mongodb",
                "firebase",
                "redis",
                "cassandra",
                "neo4j",
                "couchdb",
                "dynamodb",
                "couchbase",
                "firestore",
            ],
            "C# et .NET": [
                "c#",
                ".net",
                "dotnet",
                "asp.net",
                "wcf",
                "entity framework",
                "wpf",
                "aspnet",
                "entityframework",
                "linq",
            ],
            "Cloud et DevOps": [
                "aws",
                "azure",
                "gcp",
                "kubernetes",
                "terraform",
                "ansible",
                "jenkins",
                "helm",
                "cloud",
                "pipeline",
                "argocd",
            ],
        },
    },
    "TC": {
        "nom_export": "tc",
        "keywords": ["techniques de commercialisation", "commercial", "vente", "business developer", "marketing"],
        "etudes": build_etudes(
            "BUT Techniques de Commercialisation",
            ["but techniques de commercialisation", "but tc", "techniques de commercialisation", "tc"],
            levels=[2, 3],
        ),
        "competences": {
            "Vente": ["vente", "commercial", "prospection", "négociation", "negociation"],
            "Marketing": ["marketing", "étude de marché", "etude de marche", "campagne"],
            "Relation client": ["relation client", "crm", "satisfaction client", "fidélisation", "fidelisation"],
            "Business development": [
                "business development",
                "business developer",
                "développement commercial",
                "developpement commercial",
            ],
            "Communication": ["communication", "réseaux sociaux", "reseaux sociaux"],
            "Logiciels CRM": ["salesforce", "hubspot", "zendesk", "pipedrive"],
            "Stratégie et Canaux": [
                "b2b",
                "b2c",
                "btob",
                "btoc",
                "e-commerce",
                "merchandising",
                "retail",
                "omnicanal",
                "phoning",
            ],
        },
    },
    "GEII": {
        "nom_export": "geii",
        "keywords": [
            "electronique",
            "electrotechnique",
            "automatisme",
            "informatique industrielle",
            "robotique",
            "genie electrique",
        ],
        "etudes": build_etudes(
            "BUT Génie Électrique & Informatique Industrielle",
            [
                "but génie électrique et informatique industrielle",
                "but genie electrique et informatique industrielle",
                "but geii",
                "génie électrique et informatique industrielle",
                "genie electrique et informatique industrielle",
                "geii",
            ],
            levels=[2, 3, 5],
        ),
        "competences": {
            "Électronique": [
                "électronique",
                "electronique",
                "composant",
                "composants",
                "circuit",
                "circuits",
                "pcb",
                "fpga",
                "vhld",
                "verilog",
                "smd",
                "cms",
                "brd",
                "schematic",
                "oscilloscope",
            ],
            "Automatisme": [
                "automatisme",
                "automate",
                "automates",
                "plc",
                "siemens",
                "schneider",
                "tia portal",
                "step 7",
                "plopen",
                "codesys",
                "hmis",
                "pupitre tactile",
            ],
            "Informatique industrielle": [
                "informatique industrielle",
                "c++",
                " c ",
                "microcontrôleur",
                "microcontroleur",
                "microcontrôleurs",
                "microcontroleurs",
                "arduino",
                "raspberry",
                "rust",
                "python",
                "rtos",
                "freertos",
                "linux embarque",
                "yocto",
                "kernel",
            ],
            "Systèmes embarqués": [
                "systèmes embarqués",
                "systemes embarques",
                "embarqué",
                "embarque",
                "embedded",
                "spi",
                "i2c",
                "uart",
                "ble",
                "lora",
                "zigbee",
                "iot",
            ],
            "Électrotechnique": [
                "électrotechnique",
                "electrotechnique",
                "schéma électrique",
                "schema electrique",
                "câblage",
                "cablage",
                "basse tension",
                "haute tension",
                "hpo",
                "courant fort",
                "courants forts",
                "tableau electrique",
                "armoire electrique",
            ],
            "CAO Électrique": [
                "altium",
                "kicad",
                "solidworks electrical",
                "autocad electrical",
                "orcad",
                "eagle",
                "kicad schematics",
                "eplan",
            ],
            "Automatisation & Supervision": [
                "scada",
                "gtc",
                "gtb",
                "modbus",
                "can",
                "omron",
                "rockwell",
                "profibus",
                "profinet",
                "ethercat",
                "opc ua",
                "labview",
                "wonderware",
                "panorama",
            ],
        },
    },
}

# EXCLUSIONS AUTOMATIQUES DE MOTS-CLÉS (NÉGATIONS)
EXCLUDE_KEYWORDS = {
    "CS": [
        "animation commerciale",
        "animateur commercial",
        "animatrice commerciale",
        "developpement commercial",
        "assistant commercial",
        "assistante commerciale",
        "commerciale",
        "sales",
        "conseiller commercial",
        "conseillere commerciale",
        "marketing",
        "social media",
        "community manager",
        "digital",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "politique",
        "militaire",
        "defense",
        "officier",
        "officiers",
        "armee",
        "armees",
        "etat-major",
        "forensic",
        "audit",
        "audits",
        "communication",
        "spa",
        "massage",
        "legal",
        "juriste",
        "avocat",
        "commercial",
        "vente",
        "crm",
        "relationnel",
        "events",
        "evenementiel",
        "budgétaire",
        "budget",
        "3d",
        "jeux video",
        "logistique",
        "e-commerce",
        "rh",
        "ressources humaines",
        "droit social",
        "relations sociales",
        "droit du travail",
        "droit des affaires",
        "paie",
        "administration du personnel",
        "recrutement",
        "climat social",
        "accords collectifs",
        "rse",
        "social manager",
        "communication digitale",
        "webmarketing",
        "seo",
        # Exclusions corporatistes issues de l'audit de diagnostic
        "cadres",
        "cadres dirigeants",
        "polyvalent",
        "polyvalente",
        "assistant de direction",
        "assistante de direction",
        "assistant manager",
        "assistante manager",
        "direction",
        "manager",
        "gpme",
        "pme",
        # Anti-faux-positifs : postes juridiques, techniques, pilotage administratif
        "juridique",
        "contentieux",
        "homologation",
        "pilotage de projet",
        "intelligence artificielle",
        "chargé de mission pilotage",
        "charge de mission pilotage",
    ],
    "GEA": [
        "developpeur",
        "technicien reseau",
        "social manager",
        "educateur",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "politique",
        "defense",
        "vendeur",
        "vendeuse",
        "caissier",
        "caissiere",
        "magasin",
        "officier",
        "officiers",
        "armee",
        "armees",
        "etat-major",
        "administration système",
        "administration systeme",
        "cyberdefense",
        "cyberguerre",
        "cybersécurité",
        "cybersecurite",
        "ingénieur mécanique",
        "ingenieur mecanique",
        # Exclusions chirurgicales de bruits d'exécution sans intérêt de gestion
        "télévendeur",
        "télévendeuse",
        "televendeur",
        "televendeuse",
        "vendeur en magasin",
        "conseiller de vente",
        "conseillere de vente",
        "magasinier",
        "magasiniere",
        "cariste",
        "préparateur de commande",
        "preparateur de commande",
        "chauffeur",
        "livreur",
        "serveur",
        "serveuse",
        "cuisinier",
        "cuisiniere",
        "plongeur",
        "plongeuse",
        "manutentionnaire",
        "hôte de caisse",
        "hôtesse de caisse",
        "hote de caisse",
        "hotesse de caisse",
    ],
    "GEII": [
        "ressources humaines",
        "recrutement",
        "rh",
        "comptable",
        "comptabilite",
        "communication",
        "marketing",
        "vente",
        "commercial",
        "educateur",
        "social",
        "avocat",
        "droit",
        "juridique",
        "juriste",
        "greffe",
        "greffes",
        "juridiques",
        "cottages",
        "cottage",
        "hôtel",
        "hotel",
        "batiment",
        "immobilier",
        "espaces verts",
        "climatisation",
        "plomberie",
        "chauffage",
        "helpdesk",
        "support informatique",
        "support technique informatique",
        # Exclusions chirurgicales de bruits d'hôtellerie / Helpdesk / BTP
        "veilleur de nuit",
        "réceptionniste",
        "receptionniste",
        "femme de ménage",
        "femme de menage",
        "valet de chambre",
        "plombier",
        "chauffagiste",
        "climaticien",
        "macon",
        "maçon",
        "peintre",
        "plâtrier",
        "platrier",
        "carreleur",
        "paysagiste",
        "hotline",
        "téléconseiller",
        "teleconseiller",
        "saisie informatique",
    ],
    "INFO": [
        "secretaire",
        "secretariat",
        "comptable",
        "comptabilite",
        "commercial de terrain",
        "ressources humaines",
        "recrutement",
        "rh",
        "marketing",
        "crm",
        "sales",
        "commercial",
        "commerciaux",
        "social media",
        "community manager",
        "marketing digital",
        "seo",
        # Exclusions chirurgicales de bruits non techniques (Marketing, Admin, Vente)
        "sea",
        "chargé de communication",
        "charge de communication",
        "events",
        "evenementiel",
        "infographiste",
        "webdesigner",
        "copywriter",
        "assistant administratif",
        "assistante administrative",
        "office manager",
        "secretaire de direction",
        "vendeur",
        "vendeuse",
        "caissier",
        "caissière",
        "télévendeur",
        "televente",
        "prospection commerciale",
    ],
    "INFOCOM": [
        "developpeur c++",
        "comptable",
        "automatisme",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "politique",
        "militaire",
        "defense",
        "avocat",
        "droit",
        "juridique",
        "juriste",
        "officier",
        "officiers",
        "armee",
        "armees",
        "etat-major",
        "developpeur shopify",
        "developpeur web",
        "developpeur fullstack",
        "ingénieur de production",
        # Exclusions chirurgicales de bruits d'autres BUTs (INFO, GEA, GEII, QLIO)
        "developpeur front",
        "developpeur back",
        "developpeur php",
        "développeur java",
        "administrateur systeme",
        "cybersecurite",
        "comptabilite",
        "facturation",
        "assistant rh",
        "ressources humaines",
        "operateur",
        "ouvrier",
        "cariste",
        "magasinier",
    ],
    "QLIO": [
        "developpeur front",
        "developpeur full stack",
        "frontend",
        "fullstack",
        "educateur",
        "assistant de service social",
        "comptable",
        "comptabilite",
        "vendeur",
        "vendeuse",
        "caissier",
        "caissiere",
        "magasinier",
        "equipier de vente",
        "conseiller de vente",
        "hote de caisse",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "politique",
        "avocat",
        "droit",
        "juriste",
        "developpeur",
        "dev",
        "finance",
        "finances",
        "capital",
        "capitaux",
        "economique",
        "economiques",
        "officier",
        "officiers",
        "armee",
        "armees",
        # Exclusions chirurgicales : termes de développement logiciel et langages techniques
        "developer",
        "software",
        "backend",
        "web",
        "c++",
        "java",
        "python",
    ],
    "RT": [
        "reseau de concessions",
        "reseau de concession",
        "reseau de vente",
        "reseau commercial",
        "reseau d'agences",
        "reseau d'agence",
        "reseau de boutiques",
        "comptable",
        "comptabilite",
        "ressources humaines",
        "recrutement",
        "rh",
        "salesforce",
        "social manager",
        "marketing",
        "vente",
        "commercial",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "communication",
        "presse",
        "crm",
        "avocat",
        "droit",
        "juridique",
        "juriste",
        "juridiques",
        "tresor",
        "tresors",
        "finance",
        "finances",
        "greffe",
        "greffes",
    ],
    "SD": [
        "comptable",
        "comptabilite",
        "secretaire",
        "secretariat",
        "saisie de donnees",
        "assistant administratif",
        "assistante administrative",
        "ressources humaines",
        "recrutement",
        "rh",
        "sales",
        "commercial",
        "comptable pur",
        "assistant rh",
        "charge de recrutement",
        "paie",
        "fiscalite",
        # Exclusions chirurgicales : bruits RH/Finance/Dev/Industriel
        "hr",
        "sirh",
        "office manager",
        "seo",
        "social media",
        "community manager",
        "growth marketing",
        "financier",
        "financière",
        "finance",
        "consolidation",
        "developpement logiciel",
        "génie logiciel",
        "genie logiciel",
        "fullstack",
        "front-end",
        "frontend",
        "backend",
        "back-end",
        "testeur",
        "testeuse",
        "qa",
        "alliages",
        "aluminium",
        "matériaux",
        "materiaux",
    ],
    "TC": [
        "developpeur systeme",
        "technicien electronique",
        "câbleur",
        "ambassade",
        "consulat",
        "senat",
        "otan",
        "politique",
        "developpeur",
        "dev",
        "fullstack",
        "backend",
        "frontend",
        "java",
        "c++",
        # Exclusions chirurgicales : métiers techniques hors commerce
        "froid commercial",
        "après-vente",
        "apres-vente",
        "maintenance",
        "cvc",
        "frigoriste",
        "mécanicien",
        "mecanique",
        "automobile",
        "motocycles",
        "vélos",
        "velos",
        "domotique",
        "gtb",
        "électro stimulation",
        "electro stimulation",
        "cuisine",
    ],
}

for dept_key, excludes in EXCLUDE_KEYWORDS.items():
    if dept_key in CONFIGS:
        CONFIGS[dept_key]["exclude_keywords"] = excludes

